import exceptions.Ex;

public class Errthrower {
    public void errThrow() throws Ex {
        throw new Ex("ошибка");
    }
}
